### PR TITLE
Support Python 3.7+

### PR DESCRIPTION
**Pull request by asvetlov**

### CODE REVIEW

**Comment by rexzhang** [comment]
i have merged your PR to my project https://github.com/rexzhang/aiomemcached/commit/d284f6c97f66664200b275485468a788c9459d79

**Comment by jkeys089** [comment]
@asvetlov We're currently blocked from upgrading to python 3.10 and I *believe* this change would solve the issue. Is there anything we can do to help you with this?

**Comment by Dreamsorcerer** [comment]
We need the CI working again, which requires migrating from Travis to Github. If you want to give that a try, you could start by looking at the CI in other aio-libs projects. For example, aiohttp-session was recently updated: https://github.com/aio-libs/aiohttp-session/blob/master/.github/workflows/ci.yaml

Once the CI is working, then we can quickly go through fixes etc. to get a 3.10 compatible release out.

**Comment by jkeys089** [comment]
@Dreamsorcerer thanks for the reply! I've created a [PR](https://github.com/aio-libs/aiomcache/pull/235).

**Comment by Dreamsorcerer** [comment]
Alright, this PR basically just updates the ancient syntax, so I'll just merge it with the CI changes together.

**Pull request merged**
