### PR TITLE
WIP use deque instead of asyncio.Queue

### LINKED ISSUE #43: connection pool misbehaving with task cancellation
Script to reproduce: https://github.com/argaen/aiocache/issues/196#issuecomment-296765692

### PR DESCRIPTION
**Pull request by argaen**
The MR fixes #43 (related https://github.com/argaen/aiocache/issues/196)

Deque doesn't have context switches for the coroutines and makes the flow of acquiring connection more atomic.

Script I've been using to test:

```python
import uuid
import logging
import asyncio
import aiomcache

from aiohttp import web

logger = logging.getLogger(__name__)


class CacheManager:
    def __init__(self):
        self.cache = aiomcache.Client("127.0.0.1", 11211, pool_size=4)

    async def get(self, key):
        return await asyncio.wait_for(self.cache.get(key), 0.1)

    async def set(self, key, value):
        return await asyncio.wait_for(self.cache.set(key, value), 0.1)


async def handler_get(req):
    try:
        data = await req.app['cache'].get(b'testkey')
        print("Pool:" + str(len(req.app['cache'].cache._pool._pool)))
        print("Use:" + str(len(req.app['cache'].cache._pool._in_use)))
        if data:
            return web.Response(text=data.decode())
        data = str(uuid.uuid4()).encode()
        await req.app['cache'].set(b'testkey', data)
        return web.Response(text=str(data))
    except asyncio.TimeoutError:
        data = str(uuid.uuid4()).encode()
        await req.app['cache'].set(b'testkey', data)
        return web.Response(status=404)


if __name__ == '__main__':
    app = web.Application()
    app['cache'] = CacheManager()
    app.router.add_route('GET', '/', handler_get)
    web.run_app(app)
```

Do the load testing with: `ab -n 3500 -c 1000 http://127.0.0.1:8080/`.

To see the difference, change to master and repeat the load test. You can observe the server crashes and never recovers (plus the amount of errors is huge).

cc @fafhrd91 @achedeuzot I would like you to do the same tests to double check :)

### CODE REVIEW

**Comment by argaen** [comment]
maybe @popravich can also give some insights here

**Comment by argaen** [comment]
I want to do some extra changes:

- With the old implementation, try to do only the asyncio.sleep if there is no conn. With this we solve breaking the coroutine context when moving the connection to `in_use`. Also applies to the new implementation
- Add a new test that tries to create lots of connections and ensure only max_size connections are created (and only those are reused).

Thanks @pfreixes for the review

**Comment by achedeuzot** [comment]
Hi @argaen ,

I just checked out the branch of this PR (79f218bf0a650354790c5d9eec31069957fe0699) and tested it with the provided script. I still get errors if the concurrency is high. I double checked that the version of aiomcache used is the one with `deque` instead of `Queue` and indeed it is.

I get errors like so and even if I then make one request per one request, it fails.

    Received GET /
    handler_post exception:
    Error handling request

Also, I can have 10 concurrent connections and it turns OK. If I increase to `-c 100` then I start seeing the errors. My `memcached` is running locally (without docker) as well as the test script and `ab`.

**Comment by argaen** [comment]
Hi @achedeuzot 
> I double checked that the version of aiomcache used is the one with deque instead of Queue and indeed it is
 
Are you sure that your script is using the correct version though? I had a couple of issues with that too.

Later I'll post the numbers I get with this MR but I have the same scenario as you: Running memcached, ab and the script locally and works fine for me. There are some requests timing out but it recovers fine (and the number of failing requests is very low).

**Comment by fafhrd91** [comment]
@argaen I haven't look into any your changes (sorry, too busy at the moment)
Just a note, asyncio Queue is slow, and in general you don't need queue if you have only one consumer.

**Comment by argaen** [comment]
@achedeuzot those are the results with the current version 79f218bf0a650354790c5d9eec31069957fe0699 using `ab -n 3500 -c 1000 http://127.0.0.1:8080/`
```python
Concurrency Level:      1000
Time taken for tests:   5.735 seconds
Complete requests:      3500
Failed requests:        24
   (Connect: 0, Receive: 0, Length: 24, Exceptions: 0)
```

Couple of things to note:
- Low amount of errors
- The server keeps working after the load test (which was the original issue).

@fafhrd91 its OK, I want to try couple of extra things but once I remove the WIP, I would appreciate a review from you or any other maintainer :)

**Comment by achedeuzot** [comment]
> Are you sure that your script is using the correct version though? I had a couple of issues with that too.
I double and triple-checked again and it's the correct commit and the script is using it (printing debug info on script launch) and I have the same issues on high concurrencies (>100 simultaneous).

I destroyed the virtualenv and created it anew to be sure and inserted debug everywhere. I also re-took the above script to be sure I didn't have some other version and I still notice the issue and the server doesn't recover. So maybe there's something else at play on my machine.

**Comment by argaen** [comment]
I'm closing this in favor of https://github.com/aio-libs/aiomcache/pull/46. Read description for more details :)

**Pull request closed without merging**
