### PR TITLE
change 2 command, use formating literals

### PR DESCRIPTION
**Pull request by ArtemIsmagilov**
I try rewrite cmd(s). this optional code maybe easier to read and work.

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Same as the previous one, I'm not convinced this is an improvement when using legacy % string formatting with nested f-string formatting.

**Comment by ArtemIsmagilov** [comment]
@Dreamsorcerer. About this PR answered in #403. This is apparently a matter of preference code. Even considering that literals themselves are faster than methods and loops, this has absolutely nothing to do with our arguments here. Therefore, this is only a point of view on formations. You can cancel this PR because it does not correspond to the vision of the future project. Thank you for leaving a comment.

**Comment by ArtemIsmagilov** [comment]
To be honest, we usually use join when we don't know how many arguments need to be converted into a byte string. however, in our case, the rigid argument notation fits very well here.

**Comment by ArtemIsmagilov** [comment]
After reading this pep, we can only suggest rewriting it with %b since this is a specification for python3. https://peps.python.org/pep-0461/#interpolation

**Comment by Dreamsorcerer** [comment]
> After reading this pep, we can only suggest rewriting it with %b since this is a specification for python3. https://peps.python.org/pep-0461/#interpolation

Yep, just what I said on the other PR, as I saw an update there first.

**Comment by ArtemIsmagilov** [comment]
> > After reading this pep, we can only suggest rewriting it with %b since this is a specification for python3. https://peps.python.org/pep-0461/#interpolation
> 
> Yep, just what I said on the other PR, as I saw an update there first.

Great, then I'll redo the PR. Thank you.

**Review by ArtemIsmagilov — COMMENTED** [review]
cool)

**Pull request merged**
