### PR TITLE
set with_cas to false for single get

### LINKED ISSUE #111: get() actually issues "gets" command on the wire
This appears to be because [_multi_get()](https://github.com/aio-libs/aiomcache/blob/ca3e79e1bf1dd262835162da3748f5515046a48b/aiomcache/client.py#L78) defaults `with_cas=True` but the callers are all written as if the default were `with_cas=False`.

### PR DESCRIPTION
**Pull request by jayzfbn**
One line quick fix for #111 
Fixes #111

### CODE REVIEW

**Comment by jayzfbn** [comment]
@thehesiod fyi

**Comment by Dreamsorcerer** [comment]
I'm not familiar with what the CAS part is, so I'll defer to @thehesiod as to whether this is correct behaviour now.

**Comment by jayzfbn** [comment]
I think we're waiting for your approval @thehesiod

**Comment by thehesiod** [comment]
@Dreamsorcerer I actually proposed this change, so I approve of it =)

**Comment by jayzfbn** [comment]
> @Dreamsorcerer I actually proposed this change, so I approve of it =)

Gotta get that green checkmark :-)

**Comment by Dreamsorcerer** [comment]
Yeah, sorry, more just me not getting back to it this week.

**Comment by Dreamsorcerer** [comment]
@jayzfbn @thehesiod If you're interested in doing a little more debugging, we seem to have some problems in aiocache when using aiomcache for the backend: https://github.com/aio-libs/aiocache/issues/585 https://github.com/aio-libs/aiocache/issues/587

**Comment by jayzfbn** [comment]
I'm currently dealing with a dying furnace at my house right now (fortunately I live in California so it's not *that* cold) but I could probably take a look at this in the coming weeks if you can wait that long.

Just to confirm we don't think this is directly related to the changes we were making just general debug/improvement, ya?

**Comment by Dreamsorcerer** [comment]
> I'm currently dealing with a dying furnace at my house right now (fortunately I live in California so it's not _that_ cold) but I could probably take a look at this in the coming weeks if you can wait that long.

Whenever you like, no rush.

> Just to confirm we don't think this is directly related to the changes we were making just general debug/improvement, ya?

I don't believe so. Most of the tests have not been running on that repository for years, so I've just been getting everything up and running again, those are the still failing parts (though there are some warnings as well, which I'm trying to resolve now).

**Pull request merged**
