### PR TITLE
Implement gets cas commands

### PR DESCRIPTION
**Pull request by argaen**
For more info on the cas cmd: https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L130

For more info on the gets cmd: https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L214

### CODE REVIEW

**Comment by fafhrd91** [comment]
thanks!

**Comment by argaen** [comment]
Np! I'll create a new PR increasing coverage or trying to merge repeated code this weekend if I have time :)

**Comment by fafhrd91** [comment]
you should get invitation to aiomcache team, it has write access to aiomcache repo

**Comment by argaen** [comment]
Got it and accepted, thanks :)

**Comment by fafhrd91** [comment]
Let's make another release after your changes to coverage.

**Pull request merged**
